### ISSUE TITLE
Lost connection to the backend never restored !

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-backend#128]
``
[2017-12-02 11:46:48 CET] ERROR: [alignak.module.backend_broker] Patch livestate for host 597d8d7d99fe63f4e3e8965e error
[2017-12-02 11:46:48 CET] ERROR: [alignak.module.backend_broker] Data: {'ls_output': u'ek3022fdj-00013 is alive (0d 4h 41m 26s)', 'ls_last_time_up': 1512211300, 'ls_last_time_down
': 1512176457, 'ls_last_time_unknown': 0, '_realm': u'597d895099fe63f4e5e8946d', 'ls_perf_data': u'Uptime=16886s', 'ls_attempt': 1, 'ls_execution_time': 0.0, 'ls_last_check': 1512
211296, 'ls_last_state_type': u'HARD', 'ls_long_output': u'', 'ls_last_hard_state_changed': 1512194503, 'ls_acknowledged': False, 'ls_state_id': 0, 'ls_acknowledgement_type': 1, '
ls_latency': 0, 'ls_downtimed': False, 'ls_last_state_changed': 1512194503.884861, 'ls_state': u'UP', 'ls_last_time_unreachable': 0, 'ls_state_type': u'HARD', 'ls_last_state': u'U
P'}
[2017-12-02 11:46:48 CET] ERROR: [alignak.module.backend_broker] Exception: Backend error code 412: {"_status": "ERR", "_error": {"message": "Client and server etags don't match",
 "code": 412}}, response: <Response [412]>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend-1.0.1-py2.7.egg/alignak_module_backend/broker/module.py", line 522, in send_to_backend
    data, headers, True)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 640, in patch
    data=data, headers=headers, inception=False
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 643, in patch
    raise BackendException(412, response.content, response)
BackendException: Backend error code 412: {"_status": "ERR", "_error": {"message": "Client and server etags don't match", "code": 412}}, response: <Response [412]>
[2017-12-02 11:46:48 CET] ERROR: [alignak.module.backend_broker] Alignak backend connection is not available. Skipping objects update.
[2017-12-02 11:46:48 CET] ERROR: [alignak.module.backend_broker] Alignak backend connection is not available. Skipping objects update.
[2017-12-02 11:46:48 CET] ERROR: [alignak.module.backend_broker] Alignak backend connection is not available. Skipping objects update.
[2017-12-02 11:46:48 CET] ERROR: [alignak.module.backend_broker] Alignak backend connection is not available. Skipping objects update.

...
...
...
...
[2017-12-02 12:03:51 CET] ERROR: [alignak.module.backend_broker] Patch livestate for service 599d124e99fe6306839541eb error
[2017-12-02 12:03:51 CET] ERROR: [alignak.module.backend_broker] Data: {'ls_next_check': 0}
[2017-12-02 12:03:51 CET] ERROR: [alignak.module.backend_broker] Exception: Backend error code 412: {"_status": "ERR", "_error": {"message": "Client and server etags don't match",
 "code": 412}}, response: <Response [412]>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend-1.0.1-py2.7.egg/alignak_module_backend/broker/module.py", line 543, in send_to_backend
    data, headers, True)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 640, in patch
    data=data, headers=headers, inception=False
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 643, in patch
    raise BackendException(412, response.content, response)
BackendException: Backend error code 412: {"_status": "ERR", "_error": {"message": "Client and server etags don't match", "code": 412}}, response: <Response [412]>
[2017-12-02 12:03:51 CET] ERROR: [alignak.module.backend_broker] Alignak backend connection is not available. Skipping objects update.
```

The backend connection is lost and never restored !!!

**Comment by mohierf** [comment]
This now looks fixed
