### ISSUE TITLE
backend arbiter exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-backend#132]
```
[2017-12-07 10:26:41 CET] ERROR: [alignak.daemons.arbiterdaemon] Module backend_arbiter get_objects raised an exception u'5a290946e8a5071fe1f954a2'. Log and continue to run
[2017-12-07 10:26:41 CET] ERROR: [alignak.daemons.arbiterdaemon] Back trace of this remove: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/daemons/arbiterdaemon.py", line 580, in load_modules_configuration_objects
    objs = inst.get_objects()
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend-1.0.1-py2.7.egg/alignak_module_backend/arbiter/module.py", line 1166, in get_objects
    self.get_services()
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend-1.0.1-py2.7.egg/alignak_module_backend/arbiter/module.py", line 768, in get_services
    service['host_name'] = self.configraw['hosts'][service['host']]
KeyError: u'5a290946e8a5071fe1f954a2'

```

**Comment by mohierf** [comment]
Same problem as the one raised for the backend broker in #131
