### ISSUE TITLE
Livestate patch exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-backend#49]
```
[2017-01-07 10:20:19 CET] ERROR: [alignak.module.backend_broker] Patch livestate for service 586fdb6855927475d8236460 error
[2017-01-07 10:20:19 CET] ERROR: [alignak.module.backend_broker] Data: {'ls_output': u'ERROR: Description table : No response from remote host "93.93.45.69".', 'ls_last_state': u'UNREACHABLE', 'ls_last_time_ok': 0, 'ls_last_time_unknown': 1483780818, '_realm': u'586fdb5f55927475d8236395', 'ls_perf_data': u'', 'ls_attempt': 3, 'ls_last_time_unreachable': 1483780818, 'ls_last_time_warning': 0, 'ls_last_check': 1483780626, 'ls_last_state_type': u'HARD', 'ls_long_output': u'', 'ls_last_hard_state_changed': 1483780218, 'ls_acknowledged': False, 'ls_state_id': 4, 'ls_last_time_critical': 0, 'ls_acknowledgement_type': 1, 'ls_latency': 0.4685080051, 'ls_downtimed': False, 'ls_last_state_changed': 1483780818.616368, 'ls_state': u'UNREACHABLE', 'ls_execution_time': 10.1838240623, 'ls_state_type': u'HARD'}
[2017-01-07 10:20:19 CET] ERROR: [alignak.module.backend_broker] Exception: Backend error code 412: {"_status": "ERR", "_error": {"message": "Client and server etags don't match", "code": 412}}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_module_backend/broker/module.py", line 402, in send_to_backend
    data, headers, True)
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client/client.py", line 617, in patch
    data=data, headers=headers, inception=False
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client/client.py", line 620, in patch
    raise BackendException(412, response.content, response)
BackendException: Backend error code 412: {"_status": "ERR", "_error": {"message": "Client and server etags don't match", "code": 412}}

```

**Comment by mohierf** [comment]
Note that the `inception` parameter is stilm True!

**Comment by mohierf** [comment]
Probably a problem because several brokers are updating the same data ... false alarm :wink:
