### ISSUE TITLE
Arbiter load exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-backend#58]
```
[2017-02-03 08:17:03 CET] INFO: [alignak.daemon] I correctly loaded my modules: [backend_arbiter]
[2017-02-03 08:17:03 CET] INFO: [alignak.module.backend_arbiter] Got 5 realms
[2017-02-03 08:17:03 CET] INFO: [alignak.module.backend_arbiter] - All
[2017-02-03 08:17:03 CET] INFO: [alignak.module.backend_arbiter] - All
[2017-02-03 08:17:03 CET] INFO: [alignak.module.backend_arbiter] - All
[2017-02-03 08:17:03 CET] ERROR: [alignak.daemons.arbiterdaemon] Instance backend_arbiter raised an exception 'NoneType' object has no attribute '__getitem__'. Log and continue to run
[2017-02-03 08:17:03 CET] ERROR: [alignak.daemons.arbiterdaemon] Back trace of this remove: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 476, in load_modules_configuration_objects
    objs = inst.get_objects()
  File "/usr/local/lib/python2.7/dist-packages/alignak_module_backend/arbiter/module.py", line 932, in get_objects
    self.get_realms()
  File "/usr/local/lib/python2.7/dist-packages/alignak_module_backend/arbiter/module.py", line 318, in get_realms
    realm['realm_members'].append(child['name'])
TypeError: 'NoneType' object has no attribute '__getitem__'

[
```

What I have in the backend:
```
cat alignak-object-list-realms.json 
[
    {
        "_all_children": [],
        "_children": [],
        "_id": "589362ca38740111f83cfac6",
        "_level": 0,
        "_parent": null,
        "_tree_parents": [],
        "alias": "",
        "default": true,
        "definition_order": 100,
        "global_critical_threshold": 5,
        "global_warning_threshold": 3,
        "hosts_critical_threshold": 5,
        "hosts_warning_threshold": 3,
        "imported_from": "unknown",
        "name": "All",
        "notes": "",
        "services_critical_threshold": 5,
        "services_warning_threshold": 3
    },
    {
        "_all_children": [],
        "_children": [],
        "_id": "589362ca38740111f76159ff",
        "_level": 0,
        "_parent": null,
        "_tree_parents": [],
        "alias": "",
        "default": true,
        "definition_order": 100,
        "global_critical_threshold": 5,
        "global_warning_threshold": 3,
        "hosts_critical_threshold": 5,
        "hosts_warning_threshold": 3,
        "imported_from": "unknown",
        "name": "All",
        "notes": "",
        "services_critical_threshold": 5,
        "services_warning_threshold": 3
    },
    {
        "_all_children": [
            "58940ed13874011f2addc4d5",
            "58940ed13874011f2c28ff71"
        ],
        "_children": [
            "58940ed13874011f2addc4d5",
            "58940ed13874011f2c28ff71"
        ],
        "_id": "589362ca38740111f69f4fa1",
        "_level": 0,
        "_parent": null,
        "_tree_parents": [],
        "alias": "",
        "default": true,
        "definition_order": 100,
        "global_critical_threshold": 5,
        "global_warning_threshold": 3,
        "hosts_critical_threshold": 5,
        "hosts_warning_threshold": 3,
        "imported_from": "unknown",
        "name": "All",
        "notes": "",
        "services_critical_threshold": 5,
        "services_warning_threshold": 3
    },
    {
        "_all_children": [],
        "_children": [],
        "_id": "58942ae83874011f2addc61a",
        "_level": 1,
        "_parent": "589362ca38740111f69f4fa1",
        "_tree_parents": [
            "589362ca38740111f69f4fa1"
        ],
        "alias": "North country",
        "default": false,
        "definition_order": 100,
        "global_critical_threshold": 5,
        "global_warning_threshold": 3,
        "hosts_critical_threshold": 5,
        "hosts_warning_threshold": 3,
        "imported_from": "alignak-backend-import",
        "name": "North",
        "notes": "",
        "services_critical_threshold": 5,
        "services_warning_threshold": 3
    },
    {
        "_all_children": [],
        "_children": [],
        "_id": "58942ae83874011f2c2900a8",
        "_level": 1,
        "_parent": "589362ca38740111f69f4fa1",
        "_tree_parents": [
            "589362ca38740111f69f4fa1"
        ],
        "alias": "South country",
        "default": false,
        "definition_order": 100,
        "global_critical_threshold": 5,
        "global_warning_threshold": 3,
        "hosts_critical_threshold": 5,
        "hosts_warning_threshold": 3,
        "imported_from": "alignak-backend-import",
        "name": "South",
        "notes": "",
        "services_critical_threshold": 5,
        "services_warning_threshold": 3
    }
]
```

**Note the 3 first realms that all have the same name and that are all the default realm!!!**

**Comment by mohierf** [comment]
I cannot explain how it is possible to have a backend in this state !

**Comment by mohierf** [comment]
Several backend app launched because of the backend `lazy-apps` parameter provoke this situation !
