### ISSUE TITLE
Exception PENDING state for a service

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-backend#63]
Because of recent modifications in the retention update from the scheduler, some times services may have the PENDING state that should be accepted in the backend:
```
[2017-02-18 17:46:05 CET] ERROR: [alignak.module.backend_broker] Exception: Backend error code 422: {"_status": "ERR", "_issues": {"ls_last_state": "unallowed value PENDING"}}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/broker/module.py", line 408, in send_to_backend
    data, headers, True)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 652, in patch
    raise BackendException(response.status_code, response.content, resp)
BackendException: Backend error code 422: {"_status": "ERR", "_issues": {"ls_last_state": "unallowed value PENDING"}}
[2017-02-18 17:46:05 CET] ERROR: [alignak.module.backend_broker] Post logcheckresult for service 589c883a6376e9e75030abd1 error
[2017-02-18 17:46:05 CET] ERROR: [alignak.module.backend_broker] Data: {'state_changed': True, '_realm': u'589c87e16376e9e75030a983', 'last_state': u'PENDING', 'latency': 0, 'service': u'589c883a6376e9e75030abd1', 'output': u'', 'downtimed': False, 'state': u'OK', 'execution_time': 0.0, 'last_check': 0, 'state_type': u'HARD', 'host': u'589c87ea6376e9e74f2e6d91', 'last_state_type': u'HARD', 'acknowledgement_type': 1, 'acknowledged': False, 'state_id': 0, 'long_output': u'', 'perf_data': u''}
[2017-02-18 17:46:05 CET] ERROR: [alignak.module.backend_broker] Exception: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/broker/module.py", line 429, in send_to_backend
    response = self.backend.post('logcheckresult', data)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 549, in post
    raise BackendException(error['code'], error['message'], resp)
BackendException: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s)
```

**Comment by mohierf** [comment]
This issue has been reported to the alignak backend repository (more appropriate)
