### ISSUE TITLE
Broker module exception - ack persistent

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-backend#65]
```
[2017-03-07 14:23:36 CET] ERROR: [alignak.basemodule] [backend_broker] main function exception: 'persistent'
Traceback (most recent call last):
  File "/root/git/alignak/alignak/basemodule.py", line 412, in _main
    self.main()
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/broker/module.py", line 573, in main
    self.manage_brok(b)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/broker/module.py", line 464, in manage_brok
    self.update_actions(brok)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_backend/broker/module.py", line 546, in update_actions
    where['persistent'] = bool(brok.data['persistent'])
KeyError: 'persistent'

```

**Comment by mohierf** [comment]
The `persistent` attribute of an acknowledge has been removed in recent alignak broks modification (#700).
